
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'
export const SET_TASKS_TO_LS = 'SET_TASKS_TO_LS'
export const FETCH_TASKS_FROM_LS = 'FETCH_TASKS_FROM_LS'
export const DELETE_TASK_HANDLER = 'DELETE_TASK_HANDLER'
export const CLICK_TASK_DONE = 'CLICK_TASK_DONE'
export const DELETE_ALL_TASKS = 'DELETE_ALL_TASKS'
export const CREATE_NEW_TASK = 'CREATE_NEW_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'